# Override configuration for S3-based storage.
# Configures the stack to persist data in AWS S3 buckets.
# Usage: docker-compose -f docker-compose.yml -f docker-compose.s3.yml up --build -d

services:
  alloy:
    volumes:
      - ./alloy/s3_config.alloy:/etc/alloy/config.alloy

  tempo:
    volumes:
      - ./tempo/tempo_s3.yaml:/etc/tempo.yaml

  loki:
    volumes:
      - ./loki/loki_s3.yml:/etc/loki/loki.yaml
