# docker-compose -f docker-compose.yml -f docker-compose.s3.yml up --build -d alloy tempo loki grafana

services:
  alloy:
    volumes:
      - ./alloy/s3_config.alloy:/etc/alloy/config.alloy

  tempo:
    volumes:
      - ./tempo/tempo_s3.yaml:/etc/tempo.yaml

  loki:
    volumes:
      - ./loki/loki_s3.yml:/etc/loki/loki.yaml
